apiVersion: consul.hashicorp.com/v1alpha1
kind: IngressGateway
metadata:                                                                               
  name: my-ingress-gateway
  namespace: default                                                                    
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:             
  listeners:          
  - port: 443      
    protocol: http
    services:
    - name: foo
      namespace: bar     
